services:
  - type: web
    name: trustagent-nextjs
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PRIVATE_KEY
        sync: false
      - key: INFURA_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
    rootDir: .
